version: '3.8'

services:
  frontend:
    container_name: reelstream-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Frontend running on port 3001
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local # Load environment variables from .env.local
    depends_on:
      - backend

  backend:
    container_name: reelstream-backend
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000" # Backend API running on port 3000
      - "3002:3002"
    command: npm start
    environment:
      - NODE_ENV=development

networks:
  default:
    name: reelstream-network
